@url=http://localhost:8000/api

### Register User
POST {{url}}/users/register
Content-Type: application/json

{
    "user_name": "vutran43a",
    "email": "tranducvu43a@gmai.com",
    "password": "123456a",
    "confirm": "123456a"
}

### Login User
POST {{url}}/users/login
Content-Type: application/json

{
    "user_name": "vutran123",
    "password": "123123a"
}

### Get users by username
GET {{url}}/users?user_name=v
x-token: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzNkYTNlNGJkZmZmYWYwOGQ0ZDg5YjgiLCJpYXQiOjE3MzMyOTEzNTksImV4cCI6MTczMzI5ODU1OX0.yXi8oxm81SWqLbt2FLcDv6bsERYRhSuDusnjfF8TzvSR3YoOevue-9_5vvFwDfV1ndncOHYij44rLLdaUb1boetAWy2s8j1r_OKBYmrMOBjTIB2XJxZlY87OAw2R5bL0jtNna2BHV9RFEegn8J1FSTLG-pi-Ie9iRwwvw4MgLEYMtwQbyy9CIlDtnWBNNY-JsnM1yWFQyaoAQEAaAGzZcO2z77doQVn91ECIx2nD-z2QStximGxXkO4O8lqV1JQ3Q0eyIGxSbbOTIRR3LAfvFspIibkPL4D9MYXFcSLH3kGG87ydpireOOdP8pLZNFajehyZK0pgUE0CRi4S9COxNg

### Follow user 
PATCH {{url}}/users/673da45bbdfffaf08d4d89bf/follow
x-token: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzNkYTNlNGJkZmZmYWYwOGQ0ZDg5YjgiLCJpYXQiOjE3MzMyOTc2NDksImV4cCI6MTczMzMwNDg0OX0.YxeG-QihxY95GZSzACZ5KJCj4s5FTCTLpgSX_xcPsmFxI_ZurfYZoixuf1TvVFrTznkK25oMeXTDkGtb2cSfRHBOsb3MB7QqEjg8xoVG1l503MZ-Ery_kOmUBB--qQp_7wqHejrAsuBq-WRLtt0Giw9kxz8yHB8o8WjH8f3sHvqqemUxVntZIALCw7UXnO8M5Gln85uxsBUk5NpG60TYkIPYhwimzuUSYLo6Hwiboybxv2zdBjDaR_EorU7Rdgc_NDsP3Og6G_NWXKuek-zKw23kQ_BDtch1IG_YA10y7ov08zD-Kmd35p6riSlmLS2ZerWmrjraAbn_gESjR9G3ow

### Unfollow user 
PATCH {{url}}/users/673da45bbdfffaf08d4d89bf/unfollow
x-token: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzNkYTNlNGJkZmZmYWYwOGQ0ZDg5YjgiLCJpYXQiOjE3MzMyOTc2NDksImV4cCI6MTczMzMwNDg0OX0.YxeG-QihxY95GZSzACZ5KJCj4s5FTCTLpgSX_xcPsmFxI_ZurfYZoixuf1TvVFrTznkK25oMeXTDkGtb2cSfRHBOsb3MB7QqEjg8xoVG1l503MZ-Ery_kOmUBB--qQp_7wqHejrAsuBq-WRLtt0Giw9kxz8yHB8o8WjH8f3sHvqqemUxVntZIALCw7UXnO8M5Gln85uxsBUk5NpG60TYkIPYhwimzuUSYLo6Hwiboybxv2zdBjDaR_EorU7Rdgc_NDsP3Og6G_NWXKuek-zKw23kQ_BDtch1IG_YA10y7ov08zD-Kmd35p6riSlmLS2ZerWmrjraAbn_gESjR9G3ow



