@url=http://localhost:8000/api

### Register User
POST {{url}}/users/register
Content-Type: application/json

{
    "user_name": "vutran43a",
    "email": "tranducvu43a@gmai.com",
    "password": "123456a",
    "confirm": "123456a"
}

### Login User
POST {{url}}/users/login
Content-Type: application/json

{
    "user_name": "vutran43a",
    "password": "123456a"
}


