@url=http://localhost:8000/api

### Upload video
POST {{url}}/videos
Content-Type: application/json

{   
    "user_id": "6739fc7620630489bd285dd3",
    "video_id": "video_sharing_app/khbpgfyzuecstq5rkeyk",
    "video_url": "https://res.cloudinary.com/dzm0nupxy/video/upload/v1732007431/video_sharing_app/khbpgfyzuecstq5rkeyk.mov",
    "title": "This is just demo title 2",
    "description": "This is just demo description 2"
}

### Get videos by user_id 
GET {{url}}/users/6739fc7620630489bd285dd3/videos

### Get videos by keyword
GET {{url}}/videos?keyword=Koko

### Get video by id
GET {{url}}/videos/673c95a008500cc926a2c0ad

### Update video by id
PATCH {{url}}/videos/673f0272b4582e1635968bdf
Content-Type: application/json
x-token: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzNkYTNlNGJkZmZmYWYwOGQ0ZDg5YjgiLCJpYXQiOjE3MzIyOTc2NzEsImV4cCI6MTczMjMwNDg3MX0.UawdHScilmk5Rhgk9doIne0bccHkvppLrcLa1_0Zh7u_fnFSmNa7sBvY9bWU_o0qXU5l6IgFbg9xgVmUVOGnoYBN69gYVGHRGl_-NuP7qmgjBDoV_O_7_hv8Em6cGvS4_a5I5IFyQV0ba6Z4JMA_fXYLA6gfgVaboV4JgQwMPVineRM6yMHKjEWkUsxD_x-twG13wZTxuDuFt2LgL39F-12YCUMkkPxXm6s2KpglEwzSVskUQQKbPyh4opTCi_rWurQip5TYA93E0CGGi5OQAU_l2JaNZ9DWeHM_Pfa5G5tCV_J2X4U39fWEaoOOQVNWHkDWbbBNbjJ6yEbZa-9riw

{
    "title": "AAAA",
    "description": "AAA" 
}

### Delete video by id
DELETE {{url}}/videos/673c95a008500cc926a2c0ad

### Like video
POST {{url}}/videos/673f0272b4582e1635968bdf/like
Content-Type: application/json
x-token: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzNkYTNlNGJkZmZmYWYwOGQ0ZDg5YjgiLCJpYXQiOjE3MzI0MzMwNDYsImV4cCI6MTczMjQ0MDI0Nn0.D5ybksDCtpgxGQm4X-Srbn9JxaK29QuqxuEbMsgbGxeSGRGIJtLXw_YcGp9ODWTB4JumpN_j0l0IWxGSWgmTB3u_fIv2yxjdvsO6Co8aFu0RQCMBND-SZFrACNzIg08HJL7pUtvRR8tYHGq7fJ9rNjg4QBWjPkpqng6Htkm-UKHhvlURs7SVq-dlorGiRqyaghjUlW3NMh1C2exkK2ZFFSsUCBwtXiowOpK-w7nLy0tcY2LVku6Sx7n9tHSM5c_1fRs2zAT0RUWKVeKdoIc2ibuDqrCq_PS81m9GGgji6Y4XGs5OqwoS8wO0JQHn0OyVuZxEa6XfQxyvPMp7Se2Buw

### Unlike video
POST {{url}}/videos/673f0272b4582e1635968bdf/unlike
Content-Type: application/json
x-token: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzNkYTNlNGJkZmZmYWYwOGQ0ZDg5YjgiLCJpYXQiOjE3MzI0MzMwNDYsImV4cCI6MTczMjQ0MDI0Nn0.D5ybksDCtpgxGQm4X-Srbn9JxaK29QuqxuEbMsgbGxeSGRGIJtLXw_YcGp9ODWTB4JumpN_j0l0IWxGSWgmTB3u_fIv2yxjdvsO6Co8aFu0RQCMBND-SZFrACNzIg08HJL7pUtvRR8tYHGq7fJ9rNjg4QBWjPkpqng6Htkm-UKHhvlURs7SVq-dlorGiRqyaghjUlW3NMh1C2exkK2ZFFSsUCBwtXiowOpK-w7nLy0tcY2LVku6Sx7n9tHSM5c_1fRs2zAT0RUWKVeKdoIc2ibuDqrCq_PS81m9GGgji6Y4XGs5OqwoS8wO0JQHn0OyVuZxEa6XfQxyvPMp7Se2Buw