const GLOBAL_TYPES = {
    ALERT: "ALERT",
    AUTH: {
        LOGIN: "LOGIN",
        LOGOUT: "LOGOUT",
        VERIFY: "VERIFY"
    },
    VIDEO: {
        UPLOAD_VIDEO: "UPLOAD_VIDEO",
        GET_MY_VIDEOS: "GET_MY_VIDEOS",
        GET_HOME_VIDEOS: "GET_HOME_VIDEOS",
        GET_OTHER_VIDEOS: "GET_OTHER_VIDEOS",
        CREATE_COMMENT: "CREATE_COMMENT",
        GET_COMMENTS: "GET_COMMENTS",
        UPDATE_COMMENT: "UPDATE_COMMENT",
        DELETE_COMMENT: "DELETE_COMMENT"
    }
};

export default GLOBAL_TYPES;
